### ISSUE TITLE
damaged .framework

### ISSUE THREAD

**Issue by Acidham** [cprecioso/alfred-soulvercore#1]
I tried to run the WF and gatekeeper blocked the workflow. 
I clicked on "Open Anyway" in System Preferences  → General

I ran the WF second time but then I am receiving the following error:

`“SoulverCore.framework” is damaged and can’t be opened. You should move it to the Bin.`

**Comment by cprecioso** [comment]
Yeah, macOS is really not liking the bare .framework folder. Once you import it, you can go into the workflow folder, open it in the Terminal, and run `xattr -r -d com.apple.quarantine .`. That should let it work.

**Comment by Acidham** [comment]
works thx!
