### ISSUE TITLE
Workflow uses its own cache directory

### ISSUE THREAD

**Issue by vitorgalvao** [cprecioso/alfred-soulvercore#3]
It looks like the Workflow uses it’s own cache directory under `~/Library/Caches`, but whenever possible Workflows should read the `alfred_workflow_cache` environment variable for the path of the cache directory to use. See [Script Environment Variables](https://www.alfredapp.com/help/workflows/script-environment-variables/).

**Comment by cprecioso** [comment]
Hi @vitorgalvao, I remodelled the code and made it take advantage of those environment variables. Can you check if it works before I publish? https://github.com/cprecioso/alfred-soulvercore/releases/tag/v1.3.0-beta.1

**Comment by vitorgalvao** [comment]
Yep, the new version is correct. Thank you for the fix.
